name: On Push Run

on: push

env:
  PYTHON_DIR: python_script

jobs:
  hello-world:
    name: Hello world
    runs-on: ubuntu-latest
    steps:
    - name: Check-out devops repository
      uses: actions/checkout@v2
      with:
        repository: abhishekd23/python_script
        token: ${{ secrets.GITHUB_TOKEN }}
        path: ${{ env.DEVOPS_DIR }}

    - name: Hello World
      run: python ${{ env.PYTHON_DIR }}/a.py
      shell: sh
